root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/connectrpc"
  cmd = "go build -o ./tmp/connectrpc ./cmd/connectrpc"
  delay = 1000
  exclude_dir = ["tmp", "vendor", "website"]
  exclude_regex = ["_test\\.go$"]
  include_dir = ["cmd/connectrpc", "internal", "proto"]
  kill_delay = "0s"
  send_interrupt = false
  stop_on_error = true

[log]
  time = false

[misc]
  clean_on_exit = true
